### PR TITLE
Capping chromium version to 4.0.0 as latest changes tests

### PR DESCRIPTION
**Pull request by psweeting1**
## What does this pull request do?

E2e pipelines are failing due to a bump in selenium driver. Fixes for M1 machine issues added to help test locally.

### CODE REVIEW

**Review by TawneeOwl — DISMISSED** [review]
Love it, best PR ever! 🚢

**Review by Pheonnexx — DISMISSED** [review]
LGTM 🚢 🎈

**Review by sarahyjja — APPROVED** [review]
LGTM

**Review by sarahyjja — APPROVED** [review]
🎈

**Review by TawneeOwl — APPROVED** [review]
Damn, nice PR, approved ❤️

**Pull request merged**
