### PR TITLE
LGA-2351: ♿️ Enable accessibility e2e tests for FALA

### PR DESCRIPTION
**Pull request by sarahyjja**
## What does this pull request do?

- Add accessibility hooks to FALA tests.
- Refactor the test and feature files.

## Any other changes that would benefit highlighting?

Check if the accessibility are all passing?

## Checklist

- [x] Provided JIRA ticket number in the title, "LGA-2351: Enable accessibility e2e tests for FALA"

### CODE REVIEW

**Review by psweeting1 — DISMISSED** [review]
LGTM, Great job.

**Comment by said-moj** [comment]
The behave tests seem to have failed

**Review by jogilder — CHANGES_REQUESTED** [review]
Could you look to refactor using this?
https://github.com/ministryofjustice/cla-end-to-end-tests/blob/ced275e40065cade4076dd05fe0e65407fc79939/behave/helper/helper_base.py#L117

**Review by MishNajam — APPROVED** [review]
LGTM

**Pull request merged**
