### PR TITLE
LGA-2705 fix scope decision test failing too often

### PR DESCRIPTION
**Pull request by BenMillar-CGI**
## What does this pull request do?

Cleans up the print statements, from the previous PR  [https://github.com/ministryofjustice/cla-end-to-end-tests/pull/124](https://github.com/ministryofjustice/cla-end-to-end-tests/pull/124), adding error messages to the assert statements to provide additional debugging context if the assertions fail.

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by psweeting1 — APPROVED** [review]
LGTM

**Review by TawneeOwl — APPROVED** [review]
LGTM :shipit:

**Review by psweeting1 — APPROVED** [review]
LGTM

**Review by TawneeOwl — APPROVED** [review]
LGTM

**Pull request merged**
