### PR TITLE
LGA-2798: Announce we’re calling from CLA

### PR DESCRIPTION
**Pull request by BenMillar-CGI**
## What does this pull request do?

- Adds end to end tests for the four journeys a user can take through the contact us page which affects the announcement warning.

## Any other changes that would benefit highlighting?

- Additional improvements to generalise testing steps.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by TawneeOwl — DISMISSED** [review]
LGTM

**Review by digitalali-moj — APPROVED** [review]

**Review by TawneeOwl — DISMISSED** [review]
LGTM

**Review by digitalali-moj — DISMISSED** [review]
Thanks for quickly fixing this!

**Review by TawneeOwl — APPROVED** [review]
LGTM :D

**Review by said-moj — APPROVED** [review]
LGTM

**Pull request merged**
